version: 0.1
AttackDistanceLimit: 4.00
BroadcastMessage: "&b梦灵之都>>&a玩家{player}因涉嫌使用外挂，故踢出游戏，请大家自重！"
KickMessage:
  - "检测系统>>"
  - ""
  - "您因为异常的攻击行为逾越了阈值！"
  - "请不要尝试使用游戏外挂！Dreamc对于外挂是零容忍！"
  - "如果您对本次系统自动处理的结果存有异议，请至论坛进行申诉！"
  - ""
  - "检测系统申诉地址"
  - "www.8ymc.com"