############################################################
# +------------------------------------------------------+ #
# |                      Permission                      | #
# +------------------------------------------------------+ #
############################################################
#open2teleport.admin                   Admin
#open2teleport.bypass                 Bypass

data:
  active: false