debug: false
config_version: 1.1
creeper:
  0:
    chance:
    drop:
  1:
    chance:
    drop:
  2:
    chance:
    drop:
  3:
    chance:
    drop:
  4:
    chance:
    drop:
  5:
    chance:
    drop:
  6:
    chance:
    drop:
pigzombie:
  0:
    chance:
    drop:
  1:
    chance:
    drop:
  2:
    chance:
    drop:
  3:
    chance:
    drop:
  4:
    chance:
    drop:
  5:
    chance:
    drop:
  6:
    chance:
    drop:
skeleton:
  0:
    chance:
    drop:
  1:
    chance:
    drop:
  2:
    chance:
    drop:
  3:
    chance:
    drop:
  4:
    chance:
    drop:
  5:
    chance:
    drop:
  6:
    chance:
    drop:
cave_spider:
  0:
    chance:
    drop:
  1:
    chance:
    drop:
  2:
    chance:
    drop:
  3:
    chance:
    drop:
  4:
    chance:
    drop:
  5:
    chance:
    drop:
  6:
    chance:
    drop:
spider:
  0:
    chance:
    drop:
  1:
    chance:
    drop:
  2:
    chance:
    drop:
  3:
    chance:
    drop:
  4:
    chance:
    drop:
  5:
    chance:
    drop:
  6:
    chance:
    drop:
zombie:
  0:
    chance:
    drop:
  1:
    chance:
    drop:
  2:
    chance:
    drop:
  3:
    chance:
    drop:
  4:
    chance:
    drop:
  5:
    chance:
    drop:
  6:
    chance:
    drop: